### PR TITLE
Added missing jniLibs for armeabi and armeabi-v7a

### PR DESCRIPTION
**Pull request by andrioid**
It wasn't running on my Android and kept complaining about epos2.so being missing. After adding the relevant directories from the ePOS SDK it worked.

### Other changes

- Added `.project` from my IDE to `.gitignore`.
- Added a `preandroid` script to the Example so that the React Native packager is reachable on Android by default
- Added a `gradle` script to the Example to make it easier to clean and do other build related stuff.

### CODE REVIEW

**Comment by tr3v3r** [comment]
Nice thanks. What Android SDK version did you use? (current 2.17.1 )

**Comment by tr3v3r** [comment]
@andrioid 
I suppose we don't need this libs for now

image

image

just **libepos2.so**
could you please remove?

**Comment by andrioid** [comment]
> Nice thanks. What Android SDK version did you use? (current 2.17.1 )

I can’t remember. The latest from Epson’s page. I’ll confirm on monday.

**Comment by andrioid** [comment]
It's 2.17.1

**Comment by tr3v3r** [comment]
Merged

**Comment by tr3v3r** [comment]
I’ll release new version to npm tomorrow @andrioid

**Pull request merged**
