### PR TITLE
WIP: update printing architecture

### PR DESCRIPTION
**Pull request by tr3v3r**
# How to test:
General instructions are [here](https://github.com/tr3v3r/react-native-esc-pos-printer/blob/main/docs/INSTALLATION.md).

To install npm package:

`npm i react-native-esc-pos-printer@4.0.0-beta.6`

 or

`yarn add react-native-esc-pos-printer@4.0.0-beta.6`

# Summary  (To be updated)
Reworked the way of printing. Fixes almost all known issues.

1) Get rid of the `init` and `instantiate` methods and introduce a new class **Printer**
2)  **Printer** is as _singleton_ instance of the printer and can be used for single and multiple printing.
3) **Printer** class provides:
      - **print queue** on JS side
      - print SDK **methods** that are now just a **proxy from native SDK**
      - **error handling** which includes description and native error code
      - proper **typing**

Example:
```javascript
const printer = new Printer({
          target: printer.target,
          deviceName: printer.deviceName,
});

const status = await printer.queue.add(async () => {
      await printer.connect();
      
      await printer.addText('Hello world!);
      await printer.addFeedLine();
      await printer.addCut();
      await printer.sendData();

      await printer.disconnect();
})
```
[Detailed example.](https://github.com/tr3v3r/react-native-esc-pos-printer/blob/arch-printer-reworked/example/src/screens/SimplePrint.tsx)
## Changelog

_In progress..._

## Migration guide

_In progress..._

## To do
- [x] Remove legacy code
- [ ] Update documentations
- [x] Test multiple printing (Thanks to @Waleed065. [Test cases](https://github.com/tr3v3r/react-native-esc-pos-printer/pull/139#issuecomment-2011835789))
- [x] Refactoring
- [ ] Validation for method properties on JS side

### CODE REVIEW

**Comment by tolypash** [comment]
Still working on implementing this to local project. Looks like it works well for now. Will keep you updated when I'm done with the refactor that is needed.

**Comment by tr3v3r** [comment]
> Still working on implementing this to local project. Looks like it works well for now. Will keep you updated when I'm done with the refactor that is needed.

Thanks. If any question appears don't hesitate to reach me.

BTW. @Waleed065 have already tested a lot of scenarios with single and multiple printing - so far so good. 
I'm waiting for final approval from him.

**Comment by Waleed065** [comment]
Have integrated this version in our PROD app and all use cases work for us.
We can consider it a stable version.
We're using LAN connections.

Use cases tested

- Multi Printing ✅
- Queue Printing ✅
- Printing On Wifi Reconnection ✅
- Printing On Printer Reconnection ✅
- Warning and errors (eg: Paper Out, Open Lid) ✅

**Comment by tolypash** [comment]
@tr3v3r Would like to clarify something. Is the intended use that I connect to all discovered printers in the beginning and stay connected, or connect to each printer to print and then disconnect each time?

**Comment by tr3v3r** [comment]
> @tr3v3r Would like to clarify something. Is the intended use that I connect to all discovered printers in the beginning and stay connected, or connect to each printer to print and then disconnect each time?

@tolypash  Both scenarios are valid. 
But, to be honest. I don't think it's a good approach to tays the printer connected all the time.

you can connect and disconnect - it's cheap action.

Or if you need to do copies you can repeat commands after connection:

```
async function print() { // your print receipt commands
      await printer.addText('Hello world!);
      await printer.addFeedLine();
      await printer.addCut();
      await printer.sendData();
}


await printer.connect(); // connect

   await print()
   awaith printer.clearCommandBuffer();
   
   await print() // copy 1
   awaith printer.clearCommandBuffer();
   
 await printer.disconnect();  // disconnect after all copies printer

```

I hope this makes sense/

**Comment by tolypash** [comment]
Yes of course, thank you. It's just that we have many devices connecting to many printers. I will implement it by connecting and disconnecting then. Thank you!

**Comment by tr3v3r** [comment]
> Yes of course, thank you. It's just that we have many devices connecting to many printers. I will implement it by connecting and disconnecting then. Thank you!

Correct. The previous implementation did the connection and disconnection under the hood by the lib, but it also added constraints because of that. So in this implementation, you can control yourself when connect and disconnect

**Comment by tr3v3r** [comment]
@Waleed065 I've released beta.2 with some small [breaking changes](https://github.com/tr3v3r/react-native-esc-pos-printer/releases/tag/v4.0.0-beta.2) and refactoring. Could you please try it out when you have time? 
P.S. After this update, no other breaking changes are planned.

**Comment by Waleed065** [comment]
> @Waleed065 I've released beta.2 with some small [breaking changes](https://github.com/tr3v3r/react-native-esc-pos-printer/releases/tag/v4.0.0-beta.2) and refactoring. Could you please try it out when you have time? P.S. After this update, no other breaking changes are planned.

Sure, I'll test it and let you know

**Comment by Waleed065** [comment]
@tr3v3r There are few issues with this update. Specifically releated to imports

Screenshot 2024-03-31 at 5 05 53 PM

Simulator Screenshot - iPhone 15 Pro - 2024-03-31 at 17 26 29

**Comment by tr3v3r** [comment]
> @tr3v3r There are few issues with this update ( beta.2 ). Specifically releated to imports
> 
> 
> 
> Screenshot 2024-03-31 at 5 05 53 PM
> 
> 
> 
> Simulator Screenshot - iPhone 15 Pro - 2024-03-31 at 17 26 29
> 
> 

I see. Can I ask you why you need this enums, can't you use PrinterConstants instead? Or it's for error handling?

**Comment by Waleed065** [comment]
> > @tr3v3r There are few issues with this update ( beta.2 ). Specifically releated to imports
> > Screenshot 2024-03-31 at 5 05 53 PM
> > Simulator Screenshot - iPhone 15 Pro - 2024-03-31 at 17 26 29
> 
> I see. Can I ask you why you need this enums, can't you use PrinterConstants instead? Or it's for error handling?

Yes I need them for error handling. Some PrinterConstants errorCodes have same error code that is why. But these should be available to import anyway

**Comment by mroswald** [comment]
Is there a need to bundle the queue into this library? We have our own queue around print jobs and `p-queue` causing strange build issues on our end. For simplicity, a more modular approach would be nice (import and use if necessary)

**Comment by tr3v3r** [comment]
> Is there a need to bundle the queue into this library? We have our own queue around print jobs and `p-queue` causing strange build issues on our end. For simplicity, a more modular approach would be nice (import and use if necessary)

I assume it is still optional since you can omit using it and call printing methods without wrapping it with the queue.

But it is still a good idea to allow the use of any type of queue. 

I'll try to make it optional. In the meantime could you please give a bit more details regarding the build issue you've mentioned?

**Comment by mroswald** [comment]
Thanks for coming back so quick! 

`PQueue` is being used in the constructor of the `Printer` class and we use a postinstall patch to remove that line. It complains about `privateMap.get is not a function`. I found a github issue around it: https://github.com/sindresorhus/p-queue/issues/198

We will try if the fix applies to us (using tslib as direct dependency) and report back to you.

**Comment by tr3v3r** [comment]
> Thanks for coming back so quick!
> 
> `PQueue` is being used in the constructor of the `Printer` class and we use a postinstall patch to remove that line. It complains about `privateMap.get is not a function`. I found a github issue around it: [sindresorhus/p-queue#198](https://github.com/sindresorhus/p-queue/issues/198)
> 
> We will try if the fix applies to us (using tslib as direct dependency) and report back to you.

Thanks for the details!

Could you please also post RN version, if you're using Hermese or not? Also if it's Bare RN or Expo

Thanks

**Comment by vsnaichuk** [comment]
@tr3v3r Hi, thank you for your work, it is a great library!
I have one question regarding the usage with new architecture. Is it necessarily to await methods like "addText", "addFeedLine", "addCut"?

**Comment by mroswald** [comment]
> Could you please also post RN version, if you're using Hermese or not? Also if it's Bare RN or Expo

We're using Bare RN with Expo modules, RN 0.71.7 and will upgrade soon to 0.73. Hermes is not yet enabled

**Comment by tr3v3r** [comment]
> > Could you please also post RN version, if you're using Hermese or not? Also if it's Bare RN or Expo
> 
> We're using Bare RN with Expo modules, RN 0.71.7 and will upgrade soon to 0.73. Hermes is not yet enabled

So, if I understood properly, if do not patch anything, the build go well?

**Comment by mroswald** [comment]
> So, if I understood properly, if do not patch anything, the build go well?

If we don't patch, the constructor of `Printer` will throw an exception (`privateMap.get is not a function`). I would say it's an issue with the bundler not bundling correct/in an expected way.

**Comment by tr3v3r** [comment]
> privateMap.get

It would be great if you could provide reproducible steps or repo. Since for me and for @Waleed065  at least no issue with that

**Comment by mroswald** [comment]
We will do further investigation next week and let you know if find anything in the build settings. I can not simply share the repo and need to set up something first.

**Comment by Waleed065** [comment]
@mroswald It's better to fork the branch and make your changes if necessary.

@tr3v3r In my use case, I did not use p-queue from within the library. Rather I installed p-queue seperately and used it. The primary reason for doing this was because in our app, we support connection with other printer brands as well so to have a similar practice with all brands, I used this approach

**Comment by Waleed065** [comment]
@tr3v3r I agree with @mroswald that there is no need for p-queue to be added within the library. It should be up to the developer how they handle queue

**Comment by tr3v3r** [comment]
@Waleed065 @mroswald The reason for that is to have a separate queue per instance, and I suppose for most of the users it will be helpful, as I can see by amount of issues related to "printer busy" errors.

**Comment by tr3v3r** [comment]
@mroswald  So, I've decided to keep **p-queue** by default in the Printer class (because of different needs). But it can be overridden and won't be included in the bundle. 

[Changes here](https://github.com/tr3v3r/react-native-esc-pos-printer/pull/139/commits/7c2047a23dbdb6cf06f4e9dc85742316db75d153)

So now, to use your queue engine, or remove it completely, you can extend from the Printer class and override two methods:
**initQueue** and **addQueueTask**

For instance, with this code, the p-queue won't be bundled.
```typescript
class CustomQueuPrinter extends Printer {
  initQueue() {} // keep init clear
  addQueueTask<T>(task: () => Promise<T>) {  noop function
    return task(); //
  } 
}
```

Or you can implement these two methods with your engine:

```typescript
class CustomQueuPrinter extends Printer {
  initQueue() {
    this.queue = new CustomQueue()
  }
  addQueueTask<T>(task: () => Promise<T>) {  
    return  this.queue.push(task) // or any other logic you need
  } 
}
```

Release beta.3 with the updates.
@Waleed065 I've made it possible to import all constants  and enums within this update

**Comment by mroswald** [comment]
Works for us now, thanks!

**Comment by tolypash** [comment]
@tr3v3r What's the process to connect android devices with bluetooth? Bluetooth doesnt seem to work anymore

**Comment by tolypash** [comment]
Hey @tr3v3r another thing I noticed is that now the printing stuff is run on the main thread, and as a result I noticed JS thread is blocked. Correct me if I'm wrong.

Lastly, do you have a bluetooth printer to test bluetooth? Because I tried a couple things, nothing working

**Comment by tolypash** [comment]
Sorry for the third comment in a row guys. I have located the issue.

With the printer TM-m30II (which supports bluetooth), it connects in the beginning and prints once normally, but then as you said @tr3v3r I should disconnect. Well, after `disconnect` the printer refuses to `connect` after that at all. Not sure why.

So I decided to just `clearCommandBuffer` for bluetooth printers instead of disconnecting and remain connected all the time

**Comment by tr3v3r** [comment]
@tolypash also it would be grate to have reproducible demo or at least code snippet and more info regarding environment you use.(platforms, os versions and etc)

**Comment by tolypash** [comment]
@tr3v3r I have emailed you :)

**Comment by tolypash** [comment]
@tr3v3r Any idea what might be causing this to print on a U220 printer?

Image from iOS

**Comment by tr3v3r** [comment]
> @tr3v3r Any idea what might be causing this to print on a U220 printer?
> 
> Image from iOS

For reference. Fix here: https://github.com/tr3v3r/react-native-esc-pos-printer/issues/144

**Comment by tr3v3r** [comment]
Just release beta.5.

1) Fixed thread blocking on Android
2) Increased timeouts for Android
3) Try to fix the issue when it's not possible to print after print error

Details: https://github.com/tr3v3r/react-native-esc-pos-printer/releases/tag/v4.0.0-beta.5

CC: @tolypash @Waleed065

**Review by tolypash — APPROVED** [review]

**Comment by Waleed065** [comment]
> Just released beta.5.
> 
> 1. Fixed thread blocking on Android
> 2. Increased timeouts for Android
> 3. Try to fix the issue when it's not possible to print after print error
> 
> Details: https://github.com/tr3v3r/react-native-esc-pos-printer/releases/tag/v4.0.0-beta.5 Thanks everyone for the help! CC: @tolypash @Waleed065 @mroswald

This version Works Geat, let release it as a stable version.

Great work @tr3v3r

**Comment by tr3v3r** [comment]
Hello everyone.

I finally started to work on documentation. And added docs on [Printer](https://github.com/tr3v3r/react-native-esc-pos-printer/blob/862821ba2c5ac669dac843b5149e509481ee79e1/docs/printer/Printer.md) class [constructor](https://github.com/tr3v3r/react-native-esc-pos-printer/blob/862821ba2c5ac669dac843b5149e509481ee79e1/docs/printer/constructor.md) and [connect](https://github.com/tr3v3r/react-native-esc-pos-printer/blob/862821ba2c5ac669dac843b5149e509481ee79e1/docs/printer/connect.md) method.
After all the methods covered, I'm about to release the 4.0.0 stable version.
**If someone wants to speed up the release, I'd appreciate any help.**

#### In general, what is needed:

Take any undocumented method and cover it. As a reference [connect](https://github.com/tr3v3r/react-native-esc-pos-printer/blob/862821ba2c5ac669dac843b5149e509481ee79e1/docs/printer/connect.md) docs can be used.

#### Rules: 

Each method must be documented by using original docs for [Android](https://github.com/tr3v3r/react-native-esc-pos-printer/blob/862821ba2c5ac669dac843b5149e509481ee79e1/docs/android_v2.27.0.pdf) and [iOS](https://github.com/tr3v3r/react-native-esc-pos-printer/blob/862821ba2c5ac669dac843b5149e509481ee79e1/docs/iOS_v2.27.0.pdf) 


CC: @tolypash @Waleed065 @mroswald  @vsnaichuk

**Comment by omarst9** [comment]
hey all, I came across this repo while trying a few things on my Epson printers but i'm having trouble connecting to either of my printers (1 Lan and 1 USB).

I'm just trying the example provided but i keep getting an Error `Printer is not initialized. Please call init() first.`

I've tried running printerInstance.init() before the queueTaks but no luck either. Any ideas why i might be getting this?

Thanks!

`
export const printSimpleReceipt = async (target, deviceName) => {
    try {
      const printerInstance = new Printer({
        target: target,
        deviceName: deviceName,
      })

      await printerInstance.addQueueTask(async () => {
        await Printer.tryToConnectUntil(
          printerInstance,
          (status) => status.online.statusCode === PrinterConstants.TRUE
        );

        await printerInstance.addText('Hello world!');
        await printerInstance.addFeedLine();
        await printerInstance.addCut();
        await printerInstance.sendData();

        await printerInstance.disconnect();
      })
   
    } catch (e) {
      throw e
  }
}`

**Comment by omarst9** [comment]
I noticed that when using an older printer (TM-T88IV) the print times out, while it prints normally on my newer TM-T88V. Even printing “Hello World” takes around 5 seconds on the older model. Has anyone experienced that?

**Comment by tr3v3r** [comment]
> I noticed that when using an older USB printer (TM-T88IV) the print times out, while it prints normally on my newer USB printer TM-T88V. Even printing “Hello World” takes around 5 seconds on the older model. Has anyone experienced that?

Please create separate issues for that case, probably you'll get an answer from contributors. Also, what I can suggest is that you can try to test printing using Epson official applications. If there is still an issue with a specific model - that means it's not lib issues thanks.

**Comment by tr3v3r** [comment]
> Hi, Can use 4.0.0 beta.6 version to print in multi printer with multi device? Now I'm try to print in multi printer with multi device, but is not working on 3.1.1 version.

Hello, @softwaredev927 

 Yes, you can. 
https://github.com/tr3v3r/react-native-esc-pos-printer/pull/139#issuecomment-2011835789

**Comment by softwaredev927** [comment]
> > Hi, Can use 4.0.0 beta.6 version to print in multi printer with multi device? Now I'm try to print in multi printer with multi device, but is not working on 3.1.1 version.
> 
> Hello, @softwaredev927
> 
> Yes, you can. [#139 (comment)](https://github.com/tr3v3r/react-native-esc-pos-printer/pull/139#issuecomment-2011835789)

Thank you. for your help.
And then now this error happened while debugging.
```js
 BUNDLE  ./index.js

error: Error: Unable to resolve module ./constants from D:\ReactNative\olouris\node_modules\react-native-esc-pos-printer\src\index.tsx:

None of these files exist:
  * node_modules\react-native-esc-pos-printer\src\constants(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  * node_modules\react-native-esc-pos-printer\src\constants\index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
> 1 | export * from './discovery';
  2 | export * from './printer';
  3 |
```

**Comment by tr3v3r** [comment]
I am happy to announce that version 4.0.0 has finally been released! 
Thanks to everyone for your support!

**Pull request merged**
